### ISSUE TITLE
train_CNN

### ISSUE THREAD

**Issue by locsp-work** [AlbertoSabater/subtitle-synchronization#3]
Your project is awesome.
I just want to ask you how the function train_CNN is written?
Thank

**Comment by AlbertoSabater** [comment]
Hi! It should be trained with the _train_dense_ function. However, _model_dense_ is the recommended one for this problem, since it includes also 1-D Convolutional layers.

**Comment by locsp-work** [comment]
Thanks, but I still don't understand why len_mfcc==1 and step_mfcc==1 like picture below,I think it should be len_mfcc!=1 and step_mfcc!=1
Can you explain me more 
https://drive.google.com/file/d/1GXXHxYAMZ7vtg11bLQUt7K4dnvjZij3d/view?usp=sharing

**Comment by AlbertoSabater** [comment]
len_mfcc == 1 create training samples of the shape (len_mfcc, #fcc_features)
len_mfcc > 1 create samples with more than one timesteps
step_mfcc is used to create training samples with overlapping between them

**Comment by locsp-work** [comment]
I understand the following:
   len_mfcc == 1 for train CNN
   len_mfcc>1 for train RNN
   function train_lstm means train according to RNN model and function train_dense means train according to CNN model, right?
If I have a mistake or misunderstanding please help
